name: xv
base: core18
icon: xv.png
grade: devel
version: 3.10a+jumbo20070520+enh20081216
summary: The classic image manipulation program
description: |
  The ubiquitous and time-honored XV is the industry-leading program for
  fast, no-nonsense image display in the X Window System. It can operate on
  images in the JPEG, PNG, GIF, TIFF, PBM, PGM, PPM, XPM, X11 bitmap, Sun
  Rasterfile, Targa, RLE, RGB, BMP, PCX, FITS, and PM formats on all known
  types of X displays.

confinement: strict

parts:
  xv:
    source: ftp://ftp.trilon.com/pub/xv/xv-3.10a.tar.gz
    plugin: dump
    override-build: |
      (cd $SNAPCRAFT_STAGE/xv-3.10a; tar cf - *) | tar xf -
      patch -p1 < $SNAPCRAFT_STAGE/xv-3.10a-jumbo-fix-enh-patch-20070520.txt
      patch -p1 < $SNAPCRAFT_STAGE/xv-3.10a-enhancements.20070520-20081216.diff
      patch -p1 < $SNAPCRAFT_STAGE/xv-3.10a-namemax.patch
      patch -p0 < $SNAPCRAFT_STAGE/xv-libpng-1.5.patch
      make CCOPTS=-O3 JP2KINC=-I$SNAPCRAFT_STAGE/include JP2KLIB="-L$SNAPCRAFT_STAGE/lib -ljasper" PREFIX=
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL PREFIX=
    build-packages:
      - gcc
      - make
      - libx11-dev
      - libxt-dev
      - libjpeg-turbo8-dev
      - libtiff-dev
      - libpng-dev
      - zlib1g-dev
    stage-packages:
      - libjpeg-turbo8
      - libx11-6
      - libpng16-16
      - libtiff5
      - libjbig0
    prime:
      - bin/*
      - share/man/man*/*
      - usr/lib/*
    after:
      - jumbo
      - patches
      - jasper

  jumbo:
    source: http://prdownloads.sourceforge.net/png-mng/xv-3.10a-jumbo-patches-20070520.tar.gz?download
    source-type: tar
    plugin: dump
    prime:
      - -*

  patches:
    source: patch/
    plugin: dump
    prime:
      - -*

  jasper:
    source: https://github.com/mdadams/jasper
    source-type: git
    source-tag: version-2.0.14
    plugin: cmake
    prime:
      - -include
      - -bin
      - -share
      - -lib/*.so
      - -lib/pkgconfig

apps:
  xv:
    command: bin/xv
    desktop: xv.desktop
    plugs:
      - home
      - x11
  bggen:
    command: bin/bggen
    plugs:
      - home
      - x11
  vdcomp:
    command: bin/vdcomp
    plugs:
      - home
  xcmap:
    command: bin/xcmap
    plugs:
      - home
      - x11
  xvpictoppm:
    command: bin/xvpictoppm
    plugs:
      - home
