name: xv
base: core18
grade: devel
version: '3.10a+20081216-cm1'
summary: The classic image manipulation program
description: |
  The ubiquitous and time-honored XV is the industry-leading program for
  fast, no-nonsense image display in the X Window System. It can operate on
  many image formats including JPEG, PNG, GIF, WebP, TIFF, PBM, PGM, PPM,
  XPM, X11 bitmap, Sun Rasterfile, Targa, BPM, RGB, BMP, PCX, FITS, and PM,
  on all known types of X displays.

confinement: strict

parts:
  xv:
    source: ftp://ftp.trilon.com/pub/xv/xv-3.10a.tar.gz
    plugin: dump
    override-build: |
      (cd $SNAPCRAFT_STAGE/xv-3.10a; tar cf - *) | tar xf -
      # Greg Roelofs jumbo patch and enhancements, 20070520
      patch -p1 < $SNAPCRAFT_STAGE/xv-3.10a-jumbo-fix-enh-patch-20070520.txt
      patch -p1 < $SNAPCRAFT_STAGE/xv-3.10a-enhancements.20070520-20081216.diff
      # LibPNG 1.5 API change fix
      patch -p0 < $SNAPCRAFT_STAGE/xv-libpng-1.5.patch
      # Gabriel Somlo's name size fix
      patch -p1 < $SNAPCRAFT_STAGE/xv-3.10a-namemax.patch
      # Mark Brader's colormap cut fix
      patch -p1 < $SNAPCRAFT_STAGE/xv-3.10a-xvcut.patch
      # Patches from GRR's collection and other sources curated by David Griffith
      for i in $SNAPCRAFT_STAGE/00*; do echo "Patch: $i"; patch -p1 < $i; done
      # Build and install
      make CCOPTS=-O3 JP2KINC=-I$SNAPCRAFT_STAGE/include JP2KLIB="-L$SNAPCRAFT_STAGE/lib -ljasper" PREFIX=
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL PREFIX=
    build-packages:
      - gcc
      - make
      - libx11-dev
      - libxt-dev
      - libxrandr-dev
      - libjpeg-turbo8-dev
      - libtiff-dev
      - libpng-dev
      - libwebp-dev
      - zlib1g-dev
    stage-packages:
      - libx11-6
      - libxt6
      - libsm6
      - libice6
      - libxrandr2
      - libjpeg-turbo8
      - libtiff5
      - libpng16-16
      - libwebp6
      - libjbig0
    prime:
      - bin/*
      - share/man/man*/*
      - usr/lib/*
    after:
      - jumbo
      - patches
      - jasper

  jumbo:
    source: http://prdownloads.sourceforge.net/png-mng/xv-3.10a-jumbo-patches-20070520.tar.gz?download
    source-type: tar
    plugin: dump
    prime:
      - -*

  patches:
    source: patch/
    plugin: dump
    prime:
      - -*

  jasper:
    source: https://github.com/mdadams/jasper
    source-type: git
    source-tag: version-2.0.14
    plugin: cmake
    prime:
      - -include
      - -bin
      - -share
      - -lib/*.so
      - -lib/pkgconfig

apps:
  xv:
    command: bin/xv
    plugs:
      - home
      - x11
      - desktop
  bggen:
    command: bin/bggen
    plugs:
      - home
      - x11
  vdcomp:
    command: bin/vdcomp
    plugs:
      - home
  xcmap:
    command: bin/xcmap
    plugs:
      - home
      - x11
  xvpictoppm:
    command: bin/xvpictoppm
    plugs:
      - home
